-- df 10.0.5 build 48069
if (not LFF_GLOBAL_STRINGS) then
	LFF_GLOBAL_STRINGS = {};
end

LFF_GLOBAL_STRINGS.enUS = {
	["RENOWN_REWARD_MOUNT_NAME_FORMAT"] = "Mount: %s"
}

LFF_GLOBAL_STRINGS.enGB = LFF_GLOBAL_STRINGS.enUS;
